version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookty_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bookty_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookty_ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bookty
      MYSQL_PASSWORD: bookty
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: bookty_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage   # 🔥 ini wajib supaya symlink jalan
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bookty_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
