#!/bin/bash
OS="$(uname -s)"

case "${OS}" in
    Linux*|Darwin*) bash ./setup.sh;;
    CYGWIN*|MINGW*|MSYS*) powershell -ExecutionPolicy Bypass -File ./setup.ps1;;
    *) echo "Unsupported OS: ${OS}"; exit 1;;
esac
